DefaultContentLanguage = "nl"
MetaDataFormat = "yaml"
Paginate = 6
SectionPagesMenu = "main"
baseURL = "https://www.robvanderdussen.com"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
theme = "ananke"
[blackfriday]
hardLineBreak = true
joinLines = false
[languages.en]
languageName = "English"
title = "Churchplanting | Rob van der Dussen"
weight = 1
[languages.nl]
languageName = "Dutch"
title = "Gemeentestichting | Rob van der Dussen"
weight = 2
[params]
background_color_class = "bg-black"
description = "New initiatives, a revolutionary message and an ancient city"
facebook = ""
favicon = ""
featured_image = "/uploads/join_the_movement.jpg"
github = ""
gitlab = ""
instagram = ""
linkedin = ""
mastodon = ""
recent_posts_number = 2
twitter = "https://twitter.com/GoHugoIO"
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
